// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDARJ55LNhXOUp54Rptj448GclhuU001E',
    appId: '1:237731937838:web:827ff0c262b8150907a9bf',
    messagingSenderId: '237731937838',
    projectId: 'fableverse-a8085',
    authDomain: 'fableverse-a8085.firebaseapp.com',
    storageBucket: 'fableverse-a8085.appspot.com',
    measurementId: 'G-KJK5DNN13S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHDWqGwjdtpChLhaAtAN3r6C2QCIodHuU',
    appId: '1:237731937838:android:5764dfd2ef8bdec707a9bf',
    messagingSenderId: '237731937838',
    projectId: 'fableverse-a8085',
    storageBucket: 'fableverse-a8085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv38v4WOou5mumLnSNXIkxTj8sNGym6YY',
    appId: '1:237731937838:ios:ff3dc0ce5d6a74c707a9bf',
    messagingSenderId: '237731937838',
    projectId: 'fableverse-a8085',
    storageBucket: 'fableverse-a8085.appspot.com',
    iosBundleId: 'com.example.fabverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv38v4WOou5mumLnSNXIkxTj8sNGym6YY',
    appId: '1:237731937838:ios:ff3dc0ce5d6a74c707a9bf',
    messagingSenderId: '237731937838',
    projectId: 'fableverse-a8085',
    storageBucket: 'fableverse-a8085.appspot.com',
    iosBundleId: 'com.example.fabverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDARJ55LNhXOUp54Rptj448GclhuU001E',
    appId: '1:237731937838:web:f24f869a6097675407a9bf',
    messagingSenderId: '237731937838',
    projectId: 'fableverse-a8085',
    authDomain: 'fableverse-a8085.firebaseapp.com',
    storageBucket: 'fableverse-a8085.appspot.com',
    measurementId: 'G-F9G0JFLVLF',
  );
}
